# PHP Web Server
web:
  # Build the image off of Dockie
  # https://github.com/robloach/dockie
  image: dockie/drupal
  # Environment variables
  environment:
    # Drupal settings
    DRUPAL_PROFILE: standard
    DRUPAL_SITE_NAME: Drupal
    DRUPAL_USER: admin
    DRUPAL_PASS: admin
    DRUPAL_DBURL: mysql://drupal:drupal@mysql:3306/drupal
  ports:
    # Host machine's port 8000 will map to Drupal's port 80
    - "8000:80"
  volumes:
    # Drupal should live in the "drupal" directory
    - ./drupal:/app
    - ./docker-compose.sh:/docker-compose.sh
  links:
    - mysql:mysql
  command: php -S 0.0.0.0:80 -t /app
  working_dir: /app
  restart: always

# MySQL Server
mysql:
  image: mysql:5.7
  environment:
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  expose:
    - "3306"
  restart: always
